name: machine-learning-env

channels:
  - gpytorch
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=3.0.0
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - comm=0.2.2
  - debugpy=1.8.14
  - decorator=5.2.1
  - deprecated=1.2.13
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.7.1
  - fsspec=2025.3.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - importlib-metadata=8.6.1
  - ipykernel=6.29.5
#  - ipython=9.1.0
#  - ipython_pygments_lexers=1.1.1
  - jaxtyping=0.3.2
  - jedi=0.19.2
  - jinja2=3.1.6
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - libabseil=20250127.0
  - libcxx=20.1.3
  - libedit=3.1.20250104
  - libffi=3.4.6
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  #- liblzma=5.8.1
  - libmpdec=4.0.0
  - libopenblas=0.3.29
  - libprotobuf=5.29.3
  - libsodium=1.0.20
  - libtorch=2.5.1
  - libuv=1.48.0
  - linear_operator=0.6
  - llvm-openmp=14.0.6
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - nomkl=3.0
  - numpy=2.2.5
  - numpy-base=2.2.5
  - openssl=3.5.0
  - opentelemetry-api=1.33.1
  - packaging=25.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.0.1
  - platformdirs=4.3.7
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - python=3.10
  - python-dateutil=2.9.0.post0
  - pytorch=2.5.1
  - pyzmq=26.4.0
  - readline=8.2
  - six=1.17.0
  - sleef=3.5.1
  - sqlite=3.45.3
  - stack_data=0.6.3
  - sympy=1.13.3
  - tk=8.6.14
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.13.2
  - tzdata=2025b
  - wadler-lindig=0.1.5
  - wcwidth=0.2.13
  - wrapt=1.17.0
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - pip:
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - filelock==3.18.0
      - fonttools==4.57.0
      - idna==3.10
      - joblib==1.4.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - kiwisolver==1.4.8
      - matplotlib==3.10.1
      - pillow==11.2.1
      - pyparsing==3.2.3
      - requests==2.32.3
      - scipy==1.15.2
      - setuptools==79.0.1
      - torch==2.7.0
      - torchaudio==2.7.0
      - torchvision==0.22.0
      - urllib3==2.4.0
      - visdom==0.2.4
      - websocket-client==1.8.0
prefix: /Users/hsdiazno/miniconda3/envs/InvertibleNNs
